import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./_styles/globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "AxBen - Go beyond limits with advanced",
  description: "Generated by Osahon Osula",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
